
language: cpp

# [skip travis] in commit message avoid rebuild
# branches:
#   except:
#     - /.*no[-_]?build.*/
# branches:
#   only:
#   - master

env: INSTALL_PREFIX="~/ci_test"

jobs:
  include:
    - name: "Ubuntu 18.04 lib build"
      os: linux
      dist: bionic
      env: PACKAGE_BUILD=ON
    - name: "Ubuntu 20.04 lib build"
      os: linux
      dist: focal
      env: PACKAGE_BUILD=ON
    - name: "Ubuntu 18.04 lib build"
      os: linux
      dist: bionic
      env: PACKAGE_BUILD=OFF
    - name: "Ubuntu 20.04 lib build"
      os: linux
      dist: focal
      env: PACKAGE_BUILD=OFF
# - stage: core_build
#   script: mkdir build && cd build && cmake -DPACKAGE_BUILD=${PACKAGE_BUILD} .. && make -j4
# - stage: core_test
#   script: ctest -j4
  # - name: "MacOS Mojave"
  #   os: osx
  # Use env to specify PACKAGE_BUILD
  # - env:
  #   - PACKAGE_BUILD=ON
  #   - PACKAGE_BUILD=OFF

# stages:
#   - core_build
#   - core_test

# before_install:
#   - skip

# install:
#   - skip

# before_script:
#   - skip

script:
  - ./ci/build_install_lib.sh "${PACKAGE_BUILD}" "${INSTALL_PREFIX}"
  - ./ci/test_lib.sh "${PACKAGE_BUILD}"
  - ./ci/build_test_consumer.sh "example" "${PACKAGE_BUILD}" "${INSTALL_PREFIX}"



# notifications:
#   email: false
# sudo: required
# before_script:
#   #

# jobs:
#   include:
#   - os: linux
#     dist: bionic
#     env:
#       - TEST="Build test"
#     addons:
#       apt:
#         # sources:
#           # - ubuntu-toolchain-r-test
#         packages:
#           - gcc
#           - g++
#           - cmake
#           # - m4
#           # - patchelf
#   - stage: build_library
#     script:
#       - mkdir build && cd build && cmake .. && make -j4
#       - ctest -j4
#   # - stage: test_library
#   #   script:
#   #       - ctest -j4
