
language: cpp

# [skip travis] in commit message avoid rebuild
# branches:
#   except:
#     - /.*no[-_]?build.*/
# branches:
#   only:
#   - master

jobs:
  include:
  - name: "Ubuntu 18.04"
    os: linux
    dist: bionic
  - name: "Ubuntu 20.04"
    os: linux
    dist: focal
  # - name: "MacOS Mojave"
  #   os: osx
  # Use env to specify PACKAGE_BUILD
  - stage: core_build
    script: mkdir build && cd build && cmake -DPACKAGE_BUILD=${PACKAGE_BUILD} .. && make -j4
  - stage: core_test
    script: ctest -j4
  # - env:
  #   - PACKAGE_BUILD=ON
  #   - PACKAGE_BUILD=OFF

stages:
  - core_build
  - core_test

# before_install:
#   - skip

# install:
#   - skip

# before_script:
#   - skip

# script:
#   - mkdir build && cd build && cmake -DPACKAGE_BUILD=${PACKAGE_BUILD} .. && make -j4
#   - ctest -j4

# notifications:
#   email: false
# sudo: required
# before_script:
#   #

# jobs:
#   include:
#   - os: linux
#     dist: bionic
#     env:
#       - TEST="Build test"
#     addons:
#       apt:
#         # sources:
#           # - ubuntu-toolchain-r-test
#         packages:
#           - gcc
#           - g++
#           - cmake
#           # - m4
#           # - patchelf
#   - stage: build_library
#     script:
#       - mkdir build && cd build && cmake .. && make -j4
#       - ctest -j4
#   # - stage: test_library
#   #   script:
#   #       - ctest -j4
