language: cpp
notifications:
  email: false
sudo: required
before_script:
  #

matrix:
  include:
  - os: linux
    dist: bionic
    env:
      - TEST="Build test"
    addons:
      apt:
        # sources:
          # - ubuntu-toolchain-r-test
        packages:
          - gcc
          - g++
          - cmake
          # - m4
          # - patchelf
  # - stage: build_library
    script:
      - cmake .. 
      - make -j4
      - ctest -j4
  # - stage: test_library
  #   script:
  #       - ctest -j4
